version: "3.8"

services:
  web:
    image: ghcr.io/sandbox-pokhara/open-hypertrophy
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: open_hypertrophy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres_data:
