[tool.isort]
src_paths = ["backend"]
line_length = 79
force_single_line = true

[tool.black]
line-length = 79
preview = true

[tool.pyright]
include = ["backend"]
typeCheckingMode = "strict"
exclude = ["**/venv", "**/migrations"]
