version: "3"

tasks:
  run:
    cmds:
      - docker run --name open_hypertrophy --net host ghcr.io/sandbox-pokhara/open-hypertrophy

  run-db:
    cmds:
      - docker run --name open_hypertrophy_db --net host -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=open_hypertrophy postgres

  build:
    cmds:
      - docker build . -t ghcr.io/sandbox-pokhara/open-hypertrophy

  publish:
    cmds:
      - docker image push ghcr.io/sandbox-pokhara/open-hypertrophy

  create-superuser:
    cmds:
      - docker exec -it open_hypertrophy python manage.py createsuperuser

  deploy:
    cmds:
      - ssh andreu-ovh -t "cd open-hypertrophy && docker compose pull && docker compose up -d"
